ALTER TABLE account CONVERT TO CHARACTER SET utf8;
ALTER TABLE account_mentions CONVERT TO CHARACTER SET utf8;
ALTER TABLE feed CONVERT TO CHARACTER SET utf8;
ALTER TABLE tweet CONVERT TO CHARACTER SET utf8;
ALTER TABLE twitter_event CONVERT TO CHARACTER SET utf8;
ALTER TABLE twittered_feed CONVERT TO CHARACTER SET utf8;